source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SABarButtonView_Example', :exclusive => true do
  pod "SABarButtonView", :path => "../"
end

target 'SABarButtonView_Tests', :exclusive => true do
  pod "SABarButtonView", :path => "../"

  
end
